# Python Exercises

In [1]:
s = "kodluyoruz"
print(s.capitalize(),
      s.count("o"),
      s.upper(),
      s.startswith("kod"),
      s.islower(),
      s.isalpha(),
      s.isdigit(),
      s.replace("kodl","uy"),
      s.isspace(),
        sep="\n")

Kodluyoruz
2
KODLUYORUZ
True
True
True
False
uyuyoruz
False


In [2]:
del s

## Lists

* mutable
* sliceable
* nestable

In [3]:
l = [*range(1,21)]
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [4]:
l[:5],l[::-10],l[19],l[::-1],l[::5]

([1, 2, 3, 4, 5],
 [20, 10],
 20,
 [20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1],
 [1, 6, 11, 16])

In [5]:
l.append(21),
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [6]:
l.extend([2,2,2,3,3])
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2, 2, 2, 3, 3]


In [7]:
l.count(2)

4

In [8]:
l.insert(0,0)
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2, 2, 2, 3, 3]


In [9]:
l.remove(0)
print(l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 2, 2, 2, 3, 3]


In [10]:
l.reverse()
print(l)

[3, 3, 2, 2, 2, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [11]:
l.pop()
print(l)

[3, 3, 2, 2, 2, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2]


In [12]:
l.pop(0)
print(l)

[3, 2, 2, 2, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2]


In [13]:
l.sort()
print(l)

[2, 2, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]


In [14]:
[1,2,2,4] + [5,2,1,5], [0]*5

([1, 2, 2, 4, 5, 2, 1, 5], [0, 0, 0, 0, 0])

In [15]:
x,y,z = [1,2,3]
x,y,z

(1, 2, 3)

In [16]:
del l,x,y,z

## Tuple

* Immutable (elemanları değiştirilemez)
* sliceable
* nestable

In [17]:
t = ('fer','hat',999,7.87, [1,2,3])
t

('fer', 'hat', 999, 7.87, [1, 2, 3])

In [18]:
t[0], t[1], t[4], t[0:2]

('fer', 'hat', [1, 2, 3], ('fer', 'hat'))

In [19]:
t2 = (1,2,3)

t + t2

# t[0] = "kod" atamasını yapamayız.


('fer', 'hat', 999, 7.87, [1, 2, 3], 1, 2, 3)

In [20]:
print(tuple([1,2,3,4,5]))

(1, 2, 3, 4, 5)


In [21]:
del t, t2

## Set

* Unique eleman
* mutable eleman barındırmaz
* eleman erişimi için indisleri yok

In [22]:
s = {1,2,(1,2,3),'a'} # Liste ya da set verseydik hata alırdık. Tuple immutable olduğu için hata vermedi
s

{(1, 2, 3), 1, 2, 'a'}

In [23]:
s2 ={'a','a','a',1,2,3,3,3,3}
s2

{1, 2, 3, 'a'}

In [24]:
string = "ferhatmetin"
set(string)

{'a', 'e', 'f', 'h', 'i', 'm', 'n', 'r', 't'}

In [25]:
k1 = {1,2,4,3,5,7,9}

k2 = {4,5,6,10,7}

print(k1 | k2) # Union (Birleşim)
print(k1 - k2) # Difference (Fark)
print(k1 & k2) # Intersection (Kesişim)
print(k1 ^ k2) # Symmetric Difference (Simetrik Fark)

{1, 2, 3, 4, 5, 6, 7, 9, 10}
{1, 2, 3, 9}
{4, 5, 7}
{1, 2, 3, 6, 9, 10}


In [26]:
k = {1,2,3,4}

print(k.add(5),
      k.difference(k1),
      k.discard(2), 
      k.remove(1) , # 1 yoksa hata verir bunun için discard kullanabiliriz
      k.intersection(k1),
      k.isdisjoint(k1), # ayrık küme mi?
      k.issubset(k1),
      k.issuperset(k1),
      
      sep='\n')

None
set()
None
None
{3, 4, 5}
False
True
False


In [27]:
del k, k1,k2,s,s2,string

## Dict

* mutable 
* unique key

In [28]:
d ={'Ferhat':88,'Ali':77,'Ayşe':95,'Ahmet':100}

d["Ferhat"]

88

In [29]:
d.keys()

dict_keys(['Ferhat', 'Ali', 'Ayşe', 'Ahmet'])

In [30]:
d.values()

dict_values([88, 77, 95, 100])

In [31]:
d.items()

dict_items([('Ferhat', 88), ('Ali', 77), ('Ayşe', 95), ('Ahmet', 100)])

In [32]:
d2 = {'Fatma':66}

d.update(d2)
d

{'Ferhat': 88, 'Ali': 77, 'Ayşe': 95, 'Ahmet': 100, 'Fatma': 66}

In [33]:
d.pop('Fatma')
d

{'Ferhat': 88, 'Ali': 77, 'Ayşe': 95, 'Ahmet': 100}

## *Args

In [34]:
def kareAl(numbers):
    
    return [e**2 for e in numbers]

kareAl([1,2,3,4,5])
    

[1, 4, 9, 16, 25]

In [35]:
def kareAl(*numbers): 
    return [e**2 for e in numbers]

kareAl(1,2,3,4,5)

[1, 4, 9, 16, 25]

## **Kwargs

Fonksiyona değişken sayıda keyword argument verebilmeyi sağlar. Dictionary olarak tutar.

In [36]:
def employees(**employee):
    print(employee)
    for e in employee.values():
        print(e)
        
employees(name="Ferhat",age=45,number=123)

{'name': 'Ferhat', 'age': 45, 'number': 123}
Ferhat
45
123


## Args ve Kwargs Beraber Kullanımı

Önce args sonra kwargs yazılması gerekir.

In [37]:
def weird(*args,**kwargs):
    res = 0
    for e in args:
        res+=e
    for k,v in kwargs.items():
        print(k,':',v)
    return res

In [38]:
weird(1,2,3,name="Ferhat",bootcamp="Kodluyoruz")

name : Ferhat
bootcamp : Kodluyoruz


6

## Unpacking

In [39]:
l = [3,4,5,6]
print(*l)

3 4 5 6


In [40]:
d1 = {'ferhat':1,'ali':2}
d2 = {'ayşe':3,'ahmet':4}

d3 = {**d1,**d2}
d3

{'ferhat': 1, 'ali': 2, 'ayşe': 3, 'ahmet': 4}

In [41]:
[*range(1,10)]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
del d1,d2,d3

## Closure

Bir fonksiyonun içinde tanımlanmış fonksiyonun, dışındaki fonksiyonun içinde tanımlanmış değişkenlere,dıştaki fonksiyon çağrılmış olsa da erişebilmesidir.

In [43]:
def outer(msg):
    msg = msg
    
    def inner():
        print(msg)
    return inner()

In [44]:
outer("hi")

hi


In [45]:
def outer():
    msg = "hi"
    
    def inner():
        print(msg)
    return inner()

In [46]:
outer()

hi


## Decorator

Başka bir fonksiyonu input olarak alırlar ve aldıkları fonksiyonu değiştirmeden ona yeni fonksiyonel özellikler eklerler.

In [47]:
def print_func():
    print('kodluyoruz')

def decorator_func(func):
    def wrapper_func(): 
        print('patika')
        return func()
    
    return wrapper_func
    

    


In [48]:
decorated_print = decorator_func(print_func)
decorated_print

<function __main__.decorator_func.<locals>.wrapper_func()>

In [49]:
decorated_print()

patika
kodluyoruz


In [50]:
@decorator_func
def print_func():
    print('patika')
    
print_func()

patika
patika


In [51]:
def print_info(name,surname):
    print(f'Name : {name},  Surname : {surname}')
print_info("Ferhat","Metin")

Name : Ferhat,  Surname : Metin


In [52]:
def decorater_func(func):
    def wrapper_func(*args):
        print('Kodluyoruz')
        return func(*args)
    return wrapper_func

In [53]:
@decorater_func
def print_info(name,surname):
    print(f'Name : {name},  Surname : {surname}')
print_info("Ferhat","Metin")

Kodluyoruz
Name : Ferhat,  Surname : Metin


## Class

In [54]:
class Employee:
    def __init__(self,name,last,age,pay):
        self.name = name
        self.last = last
        self.age = age
        self.pay = pay
    def show_info(self):
        print(f'Name : {self.name}, LastName : {self.last}')

In [55]:
emp_1 = Employee("Ferhat","Metin",18,5000)
emp_2 = Employee("Ayşe","Tak",28,3000)

In [56]:
emp_1.age

18

In [57]:
emp_2.pay

3000

In [58]:
emp_1.show_info()

Name : Ferhat, LastName : Metin


## Class Variable

Class'ta ortak olarak paylaşılan variable'lar class variable'dır. Yukarıdaki age,pay gibi attribute'lara instance variable diyorduk.

In [59]:
class Employee:
    raise_percent = 1.05
    num_emp = 0
    def __init__(self,name,last,age,pay):
        self.name = name
        self.last = last
        self.age = age
        self.pay = pay
        Employee.num_emp +=1
        
    def show_info(self):
        print(f'Name : {self.name}, LastName : {self.last}')
        
    def apply_raise(self):
        self.pay = self.pay * Employee.raise_percent

In [60]:
emp_1 = Employee("Ferhat","Metin",18,5000)
emp_2 = Employee("Ayşe","Tak",28,3000)

In [61]:
Employee.num_emp

2

In [62]:
emp_1.pay

5000

In [63]:
emp_1.apply_raise()

In [64]:
emp_1.pay

5250.0

In [65]:
emp_2.pay

3000

In [66]:
emp_3 = Employee("Ali","Ata",20,1000)

Employee.num_emp

3

In [67]:
Employee.raise_percent = 1.20

In [68]:
emp_3.apply_raise()

In [69]:
emp_3.pay

1200.0

In [70]:
emp_2.pay

3000

## Class Method ve Static Method

**Class Methodu :** ilk argüman olarak instance yerine class'ı alır ve günceller. 
Instance alsaydı sadece o employee etkilenecekti bu yüzden Employee class'ının içinde class method decorator'ı kullanarak değişikliğin hepsinde olmasını sağlarız.

**Static Method :** Instance veya class'a methodun içerisinde erişim olmuyorsa static olarak tanımlamak daha iyi olabilir. Static methodlar self olarak yani otomatik olarak bir şey vermez.

In [71]:
class Employee:
    raise_percent = 1.05
    num_emp = 0
    def __init__(self,name,last,age,pay):
        self.name = name
        self.last = last
        self.age = age
        self.pay = pay
        Employee.num_emp +=1
        
    def show_info(self):
        print(f'Name : {self.name}, LastName : {self.last}')
        
    def apply_raise(self):
        self.pay = self.pay * Employee.raise_percent
    @classmethod
    def set_raise(self,amount):
        self.raise_percent = amount
        
    @classmethod
    def from_string(cls,emp_str):
        name,last,age,pay = emp_str.split("-")
        return cls(name,last,int(age),int(pay)) # yeni çalışan yaratır ve onu döndürür
    @staticmethod
    def is_dayoff(day):
        if day in ["saturday","sunday"]:
            print("it's a dayoff")
        else:
            print("it is a work day")
        

In [72]:
emp_1 = Employee("Ferhat","Metin",18,5000)
emp_2 = Employee("Ayşe","Tak",28,3000)

In [73]:
emp_1.pay, emp_2.pay

(5000, 3000)

In [74]:
Employee.raise_percent

1.05

In [75]:
Employee.set_raise(1.20)

In [76]:
emp_1.raise_percent, emp_2.raise_percent

(1.2, 1.2)

In [77]:
emp_1.set_raise(1.3)

In [78]:
emp_2.raise_percent

1.3

In [79]:
emp_3_str = "Kübra-Al-30-4000"

In [80]:
emp_3 = Employee.from_string(emp_3_str)

In [81]:
emp_3.name, emp_3.pay

('Kübra', 4000)

In [82]:
emp_3.is_dayoff('saturday')

it's a dayoff


In [83]:
emp_1.is_dayoff('wednesday')

it is a work day


## Inheritence

In [84]:
class Employee:
    raise_percent = 1.05
    num_emp = 0
    def __init__(self,name,last,age,pay):
        self.name = name
        self.last = last
        self.age = age
        self.pay = pay
        Employee.num_emp +=1
        
    def show_info(self):
        print(f'Name : {self.name}, LastName : {self.last}')
        
    def apply_raise(self):
        self.pay = self.pay * self.raise_percent
    @classmethod
    def set_raise(self,amount):
        self.raise_percent = amount
        
    @classmethod
    def from_string(cls,emp_str):
        name,last,age,pay = emp_str.split("-")
        return cls(name,last,int(age),int(pay)) # yeni çalışan yaratır ve onu döndürür
    @staticmethod
    def is_dayoff(day):
        if day in ["saturday","sunday"]:
            print("it's a dayoff")
        else:
            print("it is a work day")

In [85]:
emp_1 = Employee("Ferhat","Metin",18,5000)
emp_2 = Employee("Ayşe","Tak",28,3000)

In [86]:
class IT(Employee): # IT'nin super class'ı Employee
    raise_percent = 1.3

In [87]:
it_1 = IT('Ceyda','Toraman',33,1000)

it_1.name, it_1.pay, IT.raise_percent

('Ceyda', 1000, 1.3)

In [88]:
it_1.__dict__

{'name': 'Ceyda', 'last': 'Toraman', 'age': 33, 'pay': 1000}

In [89]:
it_1.raise_percent,it_1.pay

(1.3, 1000)

In [90]:
it_1.apply_raise()

In [91]:
it_1.pay

1300.0

In [92]:
class IT(Employee):
    raise_percent = 1.3
    def __init__(self,name,last,age,pay,lang):
        super().__init__(name,last,age,pay)
        self.lang = lang

In [93]:
it_1 = IT('Ferhat','Metin',55,10_000,"python")

it_1.__dict__

{'name': 'Ferhat', 'last': 'Metin', 'age': 55, 'pay': 10000, 'lang': 'python'}

In [94]:
class IK(Employee):
    raise_percent = 1.1
    def __init__(self,name,last,age,pay,experience):
        super().__init__(name,last,age,pay)
        self.experience = experience
    def print_exp(self):
        print(f'This employee has {self.experience} years of experience')

In [95]:
ik_1 = IK("Bülent","Kaya",30,7000,6)

ik_1.print_exp()

This employee has 6 years of experience


In [96]:
ik_1.__dict__

{'name': 'Bülent', 'last': 'Kaya', 'age': 30, 'pay': 7000, 'experience': 6}

In [97]:
issubclass(IT,IK)

False

In [98]:
issubclass(IK,IT)

False

In [99]:
isinstance(ik_1,Employee)

True

In [100]:
isinstance(it_1,Employee)

True

## Magic Method

In [101]:
class Employee:
    raise_percent = 1.05
    num_emp = 0
    def __init__(self,name,last,age,pay):
        self.name = name
        self.last = last
        self.age = age
        self.pay = pay
        Employee.num_emp +=1
        
    def show_info(self):
        print(f'Name : {self.name}, LastName : {self.last}')
        
    def apply_raise(self):
        self.pay = self.pay * self.raise_percent
    def __str__(self):
        return f'Employee(name = {self.name}, = {self.last},age ={self.age},pay = {self.pay})'
    def __add__(self,other):
        return self.pay + other.pay
    def __len__(self):
        return len(self.name)

In [102]:
emp_1 = Employee("Elon","Musk",35,500_000)
emp_2 = Employee("Bill","Gates",45,600_000)
print(emp_1)

Employee(name = Elon, = Musk,age =35,pay = 500000)


In [103]:
emp_1 + emp_2

1100000

In [104]:
len(emp_1)

4

## Generator

In [105]:
def square_generator(l):
    for e in l:
        yield e*e
        
g = square_generator([1,2,3,4,5])

In [106]:
next(g)

1

In [107]:
next(g)

4

In [108]:
next(g)

9

In [109]:
next(g)

16

In [110]:
next(g)

25

In [111]:
g = (i**2 for i in [1,2,3,4,5])

next(g)

1

In [112]:
next(g)

4

In [113]:
g = (i**2 for i in [1,2,3,4,5])
list(g)

[1, 4, 9, 16, 25]

## Map, Lambda, Filter

In [114]:
def usAl(x,y=2):
    return x**y
usAl(3),usAl(3,3)

(9, 27)

In [115]:
usAl_new = lambda x,y:x**y

usAl_new(3,3)

27

In [116]:
list(map(lambda x:x**3,[1,2,3,4,5]))

[1, 8, 27, 64, 125]

In [117]:
list(filter(lambda x:(x**3 < 64),[1,2,3,4,5]))

[1, 2, 3]

## Diğer

- Dersteki örnekler ya da Hackerrank problem çözümlerini içeriyor

In [119]:
x=int(input("Sayı:"))

while x>0:
    print("Sayı Pozitif. Negatif bir sayı giriniz.")
    x=int(input("Sayı:"))
print("Sayı Negatif")

Sayı: 2


Sayı Pozitif. Negatif bir sayı giriniz.


Sayı: 5


Sayı Pozitif. Negatif bir sayı giriniz.


Sayı: -4


Sayı Negatif


In [120]:
[i for i in range(1,20,2)],[i for i in range(2,20,2)]

([1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [2, 4, 6, 8, 10, 12, 14, 16, 18])

In [121]:
[i+1 for i in range(10)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [122]:
for i in range(10):
    if i==5:
        break
    print(i)

0
1
2
3
4


In [123]:
for i in range(10):
    if i==5:
        continue
    print(i)

0
1
2
3
4
6
7
8
9


In [124]:
for i in "ferhatmetin":
    if i in ['e','a','i']:
        continue
    print(i)

f
r
h
t
m
t
n


In [125]:
lst=["k","o","d","l","u","y","o","r","u","z"]
lst

['k', 'o', 'd', 'l', 'u', 'y', 'o', 'r', 'u', 'z']

In [126]:
lst[0:4] = "u","y","u","m"
lst

['u', 'y', 'u', 'm', 'u', 'y', 'o', 'r', 'u', 'z']

In [127]:
lst=[100,150,175,215,245,100]
lst

[100, 150, 175, 215, 245, 100]

In [128]:
lst.remove(100)
lst

[150, 175, 215, 245, 100]

In [129]:
lst.insert(0,100)
lst

[100, 150, 175, 215, 245, 100]

In [130]:
lst.extend((250,500,250))
lst

[100, 150, 175, 215, 245, 100, 250, 500, 250]

In [131]:
del lst[0]
lst

[150, 175, 215, 245, 100, 250, 500, 250]

In [132]:
lst.append(200)
lst

[150, 175, 215, 245, 100, 250, 500, 250, 200]

In [133]:
for i in range(len(lst)):
    lst[i]=lst[i]+100
lst

[250, 275, 315, 345, 200, 350, 600, 350, 300]

In [134]:
lst2=lst.copy() # kopyasında işlem yapmazsan out of range hatası muhtemel
for i in range(len(lst)):
    if lst2[i]==350:
        del lst2[i]
lst2

IndexError: list index out of range

In [136]:
lst2=[]
for i in lst:
    if i ==350:
        continue
    lst2.append(i)
lst2

[250, 275, 315, 345, 200, 600, 300]

In [137]:
lst2.pop(1)

275

In [138]:
lst2

[250, 315, 345, 200, 600, 300]

In [139]:
lst2.pop(0) +100

350

In [140]:
lst2

[315, 345, 200, 600, 300]

In [141]:
lst2.count(300)

1

In [142]:
lst + lst2

[250, 275, 315, 345, 200, 350, 600, 350, 300, 315, 345, 200, 600, 300]

In [143]:
lst

[250, 275, 315, 345, 200, 350, 600, 350, 300]

In [144]:
lst[::-1]

[300, 350, 600, 350, 200, 345, 315, 275, 250]

In [145]:
lst.sort()

In [146]:
lst

[200, 250, 275, 300, 315, 345, 350, 350, 600]

In [147]:
lst=[[4,6,2,9],[4,3,8,5]]
lst.sort()
lst

[[4, 3, 8, 5], [4, 6, 2, 9]]

In [148]:
lst=[[1,'a',['cat'],2],[[[3]],'dog'],4,5]
lst

[[1, 'a', ['cat'], 2], [[[3]], 'dog'], 4, 5]

In [149]:
flat_list=[]
def flatten_list(data):
    
    for element in data:
      
        if type(element) == list:
            
            flatten_list(element)
        else:
            flat_list.append(element)
    return flat_list
print(flatten_list(lst))

[1, 'a', 'cat', 2, 3, 'dog', 4, 5]


In [150]:
def reverse_list(lst):
    
    lst.reverse()
    
    for i in lst:
        i.reverse()
    
    return lst
    
reverse_list([[1, 2], [3, 4], [5, 6, 7]])

[[7, 6, 5], [4, 3], [2, 1]]

In [151]:
t=((1,2),3)
t[0]

(1, 2)

In [152]:
t[0][1]

2

In [154]:
num=int(input("Kontrol edilen sayı: "))

l= [1,2,3,4]

output = False

for e in l:
    if e==num:
        output=True
        break
print(output)

Kontrol edilen sayı:  6


False


In [155]:
# Setler eleman sorgusunda ve küme işlemlerinde list ve tuple'a göre daha hızlı
# Python'da ilk dictionary'ler sonra setler oluşturulmuş.

In [156]:
s1={4,6,8,2,3}
s2={4,5,6,6,6,7,8}
s1,s2

({2, 3, 4, 6, 8}, {4, 5, 6, 7, 8})

In [157]:
fiyatlar={"Çokonat":2,"Tadelle":5,"Caramio":3}
fiyatlar["Tadelle"]

5

In [158]:
fiyatlar.values(),fiyatlar.keys(),fiyatlar.items()

(dict_values([2, 5, 3]),
 dict_keys(['Çokonat', 'Tadelle', 'Caramio']),
 dict_items([('Çokonat', 2), ('Tadelle', 5), ('Caramio', 3)]))

In [159]:
s=set()
s

set()

In [160]:
s=set([1,2,3,4,5,5,5])
s

{1, 2, 3, 4, 5}

In [161]:
s.add(6)
s

{1, 2, 3, 4, 5, 6}

In [162]:
s.remove(5)
s

{1, 2, 3, 4, 6}

In [163]:
s.discard(20)
s

{1, 2, 3, 4, 6}

In [164]:
s.discard(1)
s

{2, 3, 4, 6}

In [165]:
s1,s2

({2, 3, 4, 6, 8}, {4, 5, 6, 7, 8})

In [166]:
s1.difference(s2) #1.de olup 2.de olmayan

{2, 3}

In [167]:
s1.symmetric_difference(s2),s2.symmetric_difference(s1),

({2, 3, 5, 7}, {2, 3, 5, 7})

In [168]:
s1.intersection(s2)

{4, 6, 8}

In [169]:
s1 & s2

{4, 6, 8}

In [170]:
s1.isdisjoint(s2) # ayrık küme mi

False

In [171]:
s1.issubset(s2) # s1, s2'nin alt kümesi mi?

False

In [172]:
s1=set([1,2,3,4])
s2=set([1,2])
s1.issuperset(s2)

True

In [180]:
ogrenciler={"100":{"ad":"Ferhat","not":70},
            "101":{"ad":"Caner","not":85},
           "102":{"ad":"Ceyda","not":40}}

ogrenciler["100"]

{'ad': 'Ferhat', 'not': 70}

In [181]:
len(ogrenciler)

3

In [182]:
"100" in ogrenciler

True

In [183]:
s="selam naber ?"
s.split(" ")

['selam', 'naber', '?']

In [184]:
s="selam,naber ?"
s.split(",")

['selam', 'naber ?']

In [186]:
sep=input("Neye göre bölünsün?")

Neye göre bölünsün? ,


In [187]:
s="ali,ahmet,mehmet"
idx_lst=[]

for idx in range(len(s)):
    if s[idx]==sep:
        idx_lst.append(idx)
idx_lst

[3, 9]

In [188]:
s[:idx_lst[0]]

'ali'

In [189]:
s[idx_lst[0]+1:idx_lst[1]]

'ahmet'

In [190]:
s[idx_lst[1]+1:]

'mehmet'

In [191]:
{e for e in range(1,11)}

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [193]:
{e:e**2 for e in range(1,int(input()))}

 5


{1: 1, 2: 4, 3: 9, 4: 16}

In [194]:
l=[[10],[20,30],40,50,[60,70,80],90]
l_new=[]
for i in l:
    if type(i)==list:
        for e in i:
            l_new.append(e)
    else:
        l_new.append(i)
print(l_new)

[10, 20, 30, 40, 50, 60, 70, 80, 90]


In [198]:
l=list([*range(10)]) + [*range(10,15)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [199]:
l[::2],l[::-2]

([0, 2, 4, 6, 8, 10, 12, 14], [14, 12, 10, 8, 6, 4, 2, 0])

In [203]:
# List Comprehension HackerRank Çözümüm
x = int(input())
y = int(input())
z = int(input())
n = int(input())
print ([[a,b,c] for a in range(x+1) for b in range(y+1) for c in range(z+1) if a + b + c != n ])

 6
 3
 2
 4


[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 0], [0, 1, 1], [0, 1, 2], [0, 2, 0], [0, 2, 1], [0, 3, 0], [0, 3, 2], [1, 0, 0], [1, 0, 1], [1, 0, 2], [1, 1, 0], [1, 1, 1], [1, 2, 0], [1, 2, 2], [1, 3, 1], [1, 3, 2], [2, 0, 0], [2, 0, 1], [2, 1, 0], [2, 1, 2], [2, 2, 1], [2, 2, 2], [2, 3, 0], [2, 3, 1], [2, 3, 2], [3, 0, 0], [3, 0, 2], [3, 1, 1], [3, 1, 2], [3, 2, 0], [3, 2, 1], [3, 2, 2], [3, 3, 0], [3, 3, 1], [3, 3, 2], [4, 0, 1], [4, 0, 2], [4, 1, 0], [4, 1, 1], [4, 1, 2], [4, 2, 0], [4, 2, 1], [4, 2, 2], [4, 3, 0], [4, 3, 1], [4, 3, 2], [5, 0, 0], [5, 0, 1], [5, 0, 2], [5, 1, 0], [5, 1, 1], [5, 1, 2], [5, 2, 0], [5, 2, 1], [5, 2, 2], [5, 3, 0], [5, 3, 1], [5, 3, 2], [6, 0, 0], [6, 0, 1], [6, 0, 2], [6, 1, 0], [6, 1, 1], [6, 1, 2], [6, 2, 0], [6, 2, 1], [6, 2, 2], [6, 3, 0], [6, 3, 1], [6, 3, 2]]


In [206]:
x = int(input())
y = int(input())
z = int(input())
n = int(input())

for a in range(x+1):
    for b in range(y+10):
        for c in range(z+1):
            if a+b+c!=n:
                print(list([a,b,c]))

 1
 1
 1
 1


[0, 0, 0]
[0, 1, 1]
[0, 2, 0]
[0, 2, 1]
[0, 3, 0]
[0, 3, 1]
[0, 4, 0]
[0, 4, 1]
[0, 5, 0]
[0, 5, 1]
[0, 6, 0]
[0, 6, 1]
[0, 7, 0]
[0, 7, 1]
[0, 8, 0]
[0, 8, 1]
[0, 9, 0]
[0, 9, 1]
[0, 10, 0]
[0, 10, 1]
[1, 0, 1]
[1, 1, 0]
[1, 1, 1]
[1, 2, 0]
[1, 2, 1]
[1, 3, 0]
[1, 3, 1]
[1, 4, 0]
[1, 4, 1]
[1, 5, 0]
[1, 5, 1]
[1, 6, 0]
[1, 6, 1]
[1, 7, 0]
[1, 7, 1]
[1, 8, 0]
[1, 8, 1]
[1, 9, 0]
[1, 9, 1]
[1, 10, 0]
[1, 10, 1]


In [215]:
# String Split and Join HackerRank Çözümüm
def split_and_join(line):
    
    line=line.split(" ")
    line="-".join(line)
    return line

In [ ]:
# Lists Bölümündeki HackerRank Çözümüm
N = int(input())
l=[]
for i in range(0,N):
        inp=input()
        if inp.startswith('insert'):
            l.insert(int(inp.split()[1]),int(inp.split()[2]))
        elif inp.startswith('print'):
            print(l)
        elif inp.startswith('remove'):
            l.remove(int(inp.split()[1]))
        elif inp.startswith('append'):
            l.append(int(inp.split()[1]))
        elif inp.startswith('sort'):
            l.sort()
        elif inp.startswith('pop'):
            l.pop()
        elif inp.startswith('reverse'):
            l.reverse()

In [216]:
# Print Function HackerRank Çözümüm

n = int(input())
print("".join([str(i) for i in range(1,n+1)]))

 3


123


In [217]:
# Write a Function HackerRank Çözümüm

def is_leap(year):
    
    leap = False
    if year % 4 == 0 :
        leap=True
        if year % 100 == 0:
            leap=False
            if year % 400 ==0:
                leap=True

    
    return leap

In [218]:
#len fonksiyonu kullanmadan

string="merhaba"
count=0
for _ in string:
    count+=1
print(count)

def count_str(string):
    count=0
    for _ in string:
        count+=1
    return count

7


In [219]:
count_str("merhaba")

7

In [220]:
def freq(s):

    d={}

    for c in s:
        if c not in d:
            d[c] = 1
        else:
            d[c]+=1
    return d

freq("ferhatmetin")

{'f': 1, 'e': 2, 'r': 1, 'h': 1, 'a': 1, 't': 2, 'm': 1, 'i': 1, 'n': 1}

In [221]:
def f(s):
    if len(s) < 2:
           return ""
    else:
        res=s[:2] + s[-2:]
    return res

In [222]:
f("merhaba")

'meba'

In [223]:
inp="bababa"
res=[]
s=set()

for c in inp:
    if c in s:
        res.append('$')
    else:
        s.add(c)
        res.append(c)
res="".join(res)
print(res)

ba$$$$


In [224]:
l=["merhaba","nasılsınız","naber","hey"] #en uzun string
max_len=len(l[0]) #0 da yazabiliriz
res=l[0]
for c in l:
    if len(c)>max_len:
        max_len=len(c)
        res=c
print(res,max_len)

nasılsınız 10


In [225]:
l=[10,20,30,34]
total=0
for e in l:
    total+=e
print(total)

94


In [226]:
l=[10,20,30,34]
multi=1
for e in l:
    multi*=e
print(multi)

204000


In [227]:
l=[-10,-20,-30,-34]
mx=l[0]
for e in l:
    if e>mx:
        mx=e
print(mx)
    

-10


In [228]:
l=[-10,-20,-30,-34]
mn=l[0]
for e in l:
    if e<mn:
        mn=e
print(mn)
    

-34


In [229]:
l=[10,20,30,10,10,20,56]
l2=[]

for e in l:
    if e not in l2:
        l2.append(e)
print(l2)

[10, 20, 30, 56]


In [230]:
def f(l):
    for i in range(1,len(l)+1):
        if i not in l:
            return False
    return True

In [231]:
f([4,1,3])

False

In [232]:
front = [4,2,1] # sağladıkları katkılar

back = [2,5,3]

f = 2 #iki kişi bul katkıları max olsun

In [233]:
front = []

back = []

In [234]:
def f(front,back,f):
    
    relative_list=[]
    for i in range(len(front)):
        f=front[i]
        b=back[i]
        
        relative_ist.append(f-b)
        
    return relative_list

In [235]:
# 5i nereye koyarsam en büyük olur

x = 670
str_x=str(x)
a = str(5)
for i in range(len(str_x)):
    e=str_x[i]
    if e < a:
        res = str_x[:i] + a + str_x[i:]
res

'6750'

In [236]:
s="BAOOLLNNOLOLGBAX" #BALLOON
# Silme işlemini kaç kere silebiliriz?

s_list = list(s)
balloon_list = list("BALLOON")

In [237]:
if "BALLOON" in s:
    print(True)


In [238]:
def dict_from_str(s):
    d={}

    for e in s:
        if e not in d:
            d[e]=1
        else:
            d[e]+=1
    return d

def count_balloon(s):
    d_balloon = dict_from_str("BALLOON")
    d_s=dict_from_str(s)
    
    l=[]
    
    for key in d_balloon:
        l.append(d_s[key] // d_balloon[key])
    
    return min(l)

In [239]:
s="BAOOLLNNOLOLGBAX"

In [240]:
count_balloon(s)

2

In [241]:
a = [1,2,3]
b = [5,2,1]

# suma - ea+eb = sumb-eb+ea

In [242]:
sum_a=sum(a)
sum_b=sum(b)

diff=sum_a - sum_b
diff

-2

In [243]:
element_diff = (sum_a - sum_b) 

break_outer = False
if element_diff % 2 == 0:
    for e_a in a:
        for e_b in b:
            if e_a == e_b + (element_diff / 2):
                element_swap = [e_a, e_b]
                print(element_swap)
                break_outer = True
                break
        if break_outer:
            break
else:
    print(False)

[1, 2]


In [244]:
def swap_element(a,b):
    element_diff = (sum(a) - sum(b))

    if element_diff % 2 == 0:
        for e_a in a:
            for e_b in b:
                if e_a == e_b + (element_diff / 2):
                    return [e_a, e_b]
                    
                    
    return []

In [245]:
a = [1,2,3]
b = [5,2,1]

swap_element(a,b)

[1, 2]

In [246]:
x = [0,4,2,0]
y = [0,0,1,4]

def list_to_dict(l):
    d={}
    
    for e in l:
        if e not in d:
            d[e]=1
        else:
            d[e]+=1
            
    return d

In [247]:
s="cats AND*Dogs-are Awesome"

In [248]:
import re

In [249]:
words=[]
for e in re.split(',* |_|-|!|\+', s):
    if e.isalpha()== True:
        words.append(e)
    if e.isalpha() != True:
        for k in e.split("*"):
            if k.isalpha()==True:
                words.append(k)
            if k.isalpha()!=True:
                for p in k.split("%"):
                    words.append(p)
words_2=[]
for e in words:
    words_2.append(e.lower().capitalize())
"".join(words_2)
    


'CatsAndDogsAreAwesome'

In [250]:
inp = ["a,b,c,d", "a,b,c,d,-B,d"]

inp[0]==inp[0][0:7]

True

In [251]:
inp[0][0:7]

'a,b,c,d'

In [252]:
len(inp[0])

7

In [253]:
a=[1,2,2,3,1,2]
l=[]

d={}
for e in a:
    
    if e not in d:
        d[e] = 1
    else:
        d[e]+= 1

In [254]:
a=[1,2,2,3,1,2]
set_a=set(a)
list_a=list(set_a)

In [255]:
a

[1, 2, 2, 3, 1, 2]

In [256]:
sorted(a)

[1, 1, 2, 2, 2, 3]

In [259]:
def flatten(l,is_first=False):
    if is_first:
        global flat_m
        flat_m = []
    for e in l:
        if type(e) != list:
            flat_m.append(m)
        else:
            flatten(e)
    return flat_m

## Numpy

In [260]:
import numpy as np

In [261]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [262]:
np.zeros(3)

array([0., 0., 0.])

In [263]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [264]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [265]:
np.zeros((3,3),dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [266]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [267]:
np.full((4,4),"2.3")

array([['2.3', '2.3', '2.3', '2.3'],
       ['2.3', '2.3', '2.3', '2.3'],
       ['2.3', '2.3', '2.3', '2.3'],
       ['2.3', '2.3', '2.3', '2.3']], dtype='<U3')

In [268]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [269]:
np.arange(2,10,-2)

array([], dtype=int64)

In [270]:
np.arange(10,2,-2)

array([10,  8,  6,  4])

In [271]:
np.arange(10,2,2)

array([], dtype=int64)

In [272]:
np.linspace(1,10,15) #eşit bölecek

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [273]:
np.random.normal(0,1,10)

array([ 3.06211642, -0.58802489,  0.3264528 , -2.49062345,  0.5955221 ,
       -2.90145091,  2.78597594, -0.59505989, -0.74324656,  1.12117745])

In [274]:
np.random.normal(0,10,(3,3))

array([[-1.22136399, -5.9670871 , -2.38005841],
       [ 3.62566239,  2.82777579, 16.71458052],
       [ 2.43304403,  4.08293904, -4.30838843]])

In [275]:
np.random.randint(1,11,5)

array([9, 7, 7, 8, 9])

In [276]:
d = {}
for _ in range(20_000):
    val = np.random.randint(1,11)
    
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1
d

{3: 2007,
 10: 2082,
 8: 1986,
 5: 1998,
 1: 2033,
 7: 2018,
 9: 2051,
 6: 1952,
 4: 1932,
 2: 1941}

In [277]:
#identity matris

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [278]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [279]:
a = np.array([1,2,3,4])
b = np.array([0,1,2,3])

a*b

array([ 0,  2,  6, 12])

In [280]:
a + b

array([1, 3, 5, 7])

In [281]:
a**b

array([ 1,  2,  9, 64])

In [282]:
a*3

array([ 3,  6,  9, 12])

In [283]:
a.ndim

1

In [284]:
n = np.zeros((3,4))
n

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [285]:
n.ndim, n.shape, n.size,n.dtype

(2, (3, 4), 12, dtype('float64'))

In [286]:
n = np.eye(4,4)
n

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [287]:
n.reshape(2,8)

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [288]:
n.reshape(-1,8)

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [289]:
n[np.newaxis,:]

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]])

In [290]:
n[:,None]

array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]],

       [[0., 0., 0., 1.]]])

In [291]:
n[None,:]

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]])

In [292]:
a = np.arange(1,7)

x = a[np.newaxis,:]
x.shape

(1, 6)

In [293]:
x

array([[1, 2, 3, 4, 5, 6]])

In [294]:
a = np.array([1,2,3,4,5])

b = np.array([6,7,8,9,10])

np.concatenate([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [295]:
np.concatenate([a,b,[10,11,12]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 11, 12])

In [296]:
np.concatenate([a,b,(10,11)])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 11])

In [297]:
a

array([1, 2, 3, 4, 5])

In [298]:
b

array([ 6,  7,  8,  9, 10])

In [299]:
np.stack([a,b])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [300]:
np.stack([a,b],axis=1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [301]:
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [302]:
np.split(arr,[5,10])

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])]

In [303]:
a,b,c = np.split(arr,[5,10])
b

array([5, 6, 7, 8, 9])

In [304]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [305]:
arr = arr[np.newaxis,:]
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20]])

In [306]:
arr= arr.reshape(7,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [307]:
np.vsplit(arr,[3])

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]])]

In [308]:
np.hsplit(arr,[1])

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17],
        [19, 20]])]

In [309]:
a = np.arange(20).reshape(5,4) 

np.vsplit(a,[2,3])[1].shape

(1, 4)

In [310]:
arr = [4,1,3,8,5,4,2,3,3,6]
np.sort(arr)

array([1, 2, 3, 3, 3, 4, 4, 5, 6, 8])

In [311]:
arr

[4, 1, 3, 8, 5, 4, 2, 3, 3, 6]

In [312]:
np.argsort(arr) # Sıralanan değerlerin indexleri

array([1, 6, 2, 7, 8, 0, 5, 4, 9, 3])

In [313]:
arr[5], arr[:3],arr[-3:],arr[::-4]

(4, [4, 1, 3], [3, 3, 6], [6, 4, 1])

In [314]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [315]:
arr[0]

array([1, 2, 3])

In [316]:
arr[:,0]

array([1, 4, 7])

In [317]:
arr[1,1] = 12
arr

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [318]:
arr[0:2]

array([[ 1,  2,  3],
       [ 4, 12,  6]])

In [319]:
arr

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [320]:
arr[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [321]:
arr[:,1]

array([ 2, 12,  8])

In [322]:
a=np.arange(1,13).reshape(3,4)

In [323]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [324]:
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [325]:
a[[0]]

array([[1, 2, 3, 4]])

In [326]:
a[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [327]:
a[[1,2]][:,2]

array([ 7, 11])

## 

In [328]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [329]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [330]:
a[a<np.mean(a)]

array([1, 2, 3, 4, 5, 6])

In [331]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [332]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [333]:
a = np.array([4,6,7,2,1,3,8])
b = np.array([3,5,7,8,1,3,1])

In [334]:
a[a==b]

array([7, 1, 3])

In [335]:
flt = (a<5) | (a>7)

In [336]:
a[flt]

array([4, 2, 1, 3, 8])

In [337]:
a[~flt]

array([6, 7])

In [338]:
np.sum(flt)

5

In [339]:
np.sum(a[a>5])

21

In [340]:
np.sum(a>5)

3

In [341]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [342]:
np.sum(arr)

136

In [343]:
np.sum(arr,axis=0)

array([28, 32, 36, 40])

In [344]:
np.sum(arr,axis=1)

array([10, 26, 42, 58])

In [345]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [346]:
np.all(arr>=1)

True

In [347]:
np.all(arr>8,axis=1)

array([False, False,  True,  True])

In [348]:
np.all(arr>8,axis=0)

array([False, False, False, False])

In [349]:
a=np.arange(1,21).reshape(4,5)

np.all(a>8,axis=1)

array([False, False,  True,  True])

In [350]:
np.any(arr>5)

True

In [351]:
np.any(arr<-5)

False

In [352]:
np.any(arr>5,axis=0)

array([ True,  True,  True,  True])

In [353]:
np.any(arr<5,axis=1)

array([ True, False, False, False])

In [354]:
a=np.arange(1,21).reshape(4,5)

np.any(a>4,axis=0)

array([ True,  True,  True,  True,  True])

In [355]:
np.isin([1,2,3,8],[1,2,3,4,5,6])

array([ True,  True,  True, False])